sudo: required

language: java

services:
  - docker

branches:
  only:
    - master
    - stable

install: true

script:
  - ./gradlew clean asciidoctor

deploy:
  - provider: script
    skip_cleanup: true
    local_dir: build/asciidoctor/html5/  # or remove this line to upload from root of repo
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    on:
      branch: master
